import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.gradleup.shadow") version "9.0.0-beta2"
    `java-library`
    id("io.papermc.paperweight.userdev") version "1.7.3"
    `maven-publish`
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://jitpack.io/")
    }

    maven {
        url = uri("https://maven.citizensnpcs.co/repo")
    }

    maven {
        url = uri("https://repo.minebench.de/")
    }

    maven {
        url = uri("https://repo.dmulloy2.net/repository/public/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.org.kohsuke.github.api)
    compileOnly(libs.com.comphenix.protocol.protocollib)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.org.projectlombok.lombok)
    compileOnly(libs.org.spigotmc.spigot)
    compileOnly(libs.net.citizensnpcs.citizens.main)
    compileOnly(libs.dev.jorel.commandapi.bukkit.core)
    implementation("commons-io:commons-io:2.18.0")
    paperDevBundle("1.19.4-R0.1-SNAPSHOT")
    compileOnly("org.projectlombok:lombok:1.18.36")
    annotationProcessor("org.projectlombok:lombok:1.18.36")
    testCompileOnly("org.projectlombok:lombok:1.18.36")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.36")
}

group = "ru.primer"
version = "1.0"
description = "PrimeApi"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks {
    assemble {
        dependsOn(reobfJar) // Run reobfJar on build
    }
}

buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("com.gradleup.shadow:shadow-gradle-plugin:9.0.0-beta2")
    }
}

tasks.withType<ShadowJar> {
    destinationDirectory = File("C:\\Users\\admin\\Desktop\\Сервера для разработки\\1.19.4\\plugins")
    archiveFileName.set("PrimeApi.jar")
}